---
title: "Steno Register-based Project: {{< var project.title >}}"
author:
  - name: Marie Kempf Frydendahl
    affiliations: 
        - name: Steno Diabetes Center Aarhus
  - name: Gunnar Toft
    affiliations: 
        - name: Steno Diabetes Center Aarhus
        - name: Aarhus University
---

The sidebar contains information on the Project Database at SDCA. If
you want to browse all the variables and registers we've requested, use
the table below.

## Searchable table

```{r setup}
#| message: false
#| warning: false
#| echo: false
#| column: page
#| tbl-cap: "Registers and variables requested from DST (as a searchable table)."
library(tidyverse)
library(here)
library(glue)
library(reactable)
source(here("R/functions.R"))
needed_registers <- here("data/DST-variables.csv") %>%
  read_csv(col_types = "lddccccc") %>%
  filter(!drop | is.na(drop))

dst_variables <- read_csv(here("data/DST-variables.csv"))
dst_variables <- dst_variables %>%
  filter(
    register_id %in% unique(needed_registers$register_id)
  ) %>%
  mutate(across(ends_with("year"), str_extract, pattern = "^\\d{4}")) %>%
  mutate(
    start_year = case_when(
      is.na(variable_start_year) |
        variable_start_year == variable_end_year ~
        register_start_year,
      TRUE ~ variable_start_year
    ),
    year_range = glue::glue("{start_year} - {variable_end_year}")
  ) %>%
  mutate(across(ends_with("year"), as.numeric))


## Full variable list

```{r}
#| message: false
#| warning: false
#| echo: false
#| column: page
#| tbl-cap: "Registers and variables requested from DST (fully displayed list)."
options(knitr.kable.NA = "")
joined_registers %>% 
  knitr::kable()
```
