---
title: Getting started
description: Information about the SDCA project database and how to get access to work with research projects on the database. 
editor: 
  markdown: 
    wrap: 72
---

## Presentation

The Project database is a common database for all epidemiological and
clinical research projects affiliated to Steno Diabetes Center Aarhus.
It gives the possibility to get access to a broad range of register data
from e.g. Statistics Denmark, the Danish health data authorities and
other data sources in a minimal cost with the possibility of yearly
updates of the registers. Also there is a possibility to upload your own
data to a sub-project and link it to the register-based data sources.

## Purpose

The overall purpose of the project database is to study factors that can
help predict and understand the development of diabetes and other
chronic diseases or conditions that can be equated with chronic disease,
as well as their related consequences and complications. In addition,
the project database will form the basis of descriptive analyses in the
field of disease and health. The project database provides the basis for
creating sub-projects that fall under the overall purpose of the project
database and that use (a subset of) data included in the project
database.

## Terms of use

All users need an affiliation with SDCA to obtain direct access (not
necessarily paid employment) and need to have an active access to
Statistics Denmark.

## Contact

If you have any questions or need help please contact:

-   Marie Kempf Frydendahl
    ([maipee\@rm.dk](mailto:maipee@rm.dk){.email}):

-   Gunnar Vase Toft ([guntof\@rm.dk](mailto:guntof@rm.dk){.email}):

-   Kasper Norman ([kanoan\@rm.dk](mailto:kanoan@rm.dk){.email})

## How to get access

There are several ways to get to work on the SDCA Project database at
Statistics Denmark. If the purpose of your study fits under one of the
already existing sub-projects, you can contact the person responsible
for the project and request permission to access it. Below you can see a
short description of all existing projects in the project database.

If the purpose of your study does not fit under any of the existing
projects in the project database you can set up your own project under
the project database (provided that your purpose is aligned with the
overall purpose). On this page you can find information on the
procedures and steps you will need to follow to set up a new sub-project
under the project database.

## Overview of currently active projects in the project database

| Project number | Project title | Purpose | Project owner | Contact | Enddate |
|------------|------------|--------------|------------|------------|------------|
| **708421** | Interplay between diabetes and intergenerational transmission of health determinants over the life course | The overall aim of this project is to identify the contributions of family and early life determinants on the development, management, and care of diabetes and the diseases that may arise following a diabetes diagnosis, under a life-course framework. | Gunnar Vase Toft | [guntof\@rm.dk](mailto:guntof@rm.dk){.email} | 31.12.2030 |
| **709964** | Den aarhusianske børnekohorte for mental sundhed og længerevarende sygdom | To create a child cohort for research on mental health, long-term illnesses and conditions that can be equated with long-term illness in Danish children and adolescents. | Anette Andersen / Rasmus Møller Jørgensen | [Anette.Andersen\@rm.dk](mailto:Anette.Andersen@rm.dk){.email} / [rasmujer\@rm.dk](mailto:rasmujer@rm.dk){.email} | 31.12.2034 |
| **710017** | Registeropfølgning på Tjek Dit Helbred | To investigate what the initiation of a major health screening project means for the development of disease and later health behavior at the population level compared to non-invited citizens. | Eeva-Liisa Røssell Johansen | [eevjoh\@rm.dk](mailto:eevjoh@rm.dk){.email} | 31.12.2030 |
| **710055** | Lokalsamfund i Bevægelse | The purpose of the project is to follow the existing cohort and future cohorts of children and young people who have participated in the 'Local Communities on the Move' project or live in the participating school districts, including their parents, for research on children and young people's health, well-being and movement. The purpose is also to study the effect of the efforts in 'Local Communities on the Move', where the first follow-up is expected to take place in the fall of 2026. | Helene Kirkegaard | [helene.kirkegaard\@rm.dk](mailto:helene.kirkegaard@rm.dk){.email} | 31.12.2034 |
