---
title: "How to work with data"
description: Some general guidelines on how to work with data on a project at Statistics Denmark

---

## Project Initiation
When the project is approved by the Statistic Denmark data can be moved to the project. As disk storage is an increasing expence we aim to only have data on the project in one format. The following formats are available:

-   SAS
-   STATA
-   Parquet

If more dataformats is required at the project, an arrangement regarding that can be made . 

## How to work with data
At Statistics Denmark, you can work with data using Python, SPSS, Stata, SAS, and R. The link below provides access to both an English and a Danish guide for working with data in R at Statistics Denmark. These resources are intended for both beginners and users with some prior experience of R and Statistics Denmark's research environment. 

<div class="d-flex gap-2">

  <a href="https://steno-aarhus.github.io/registers-guide/da/00_index.html"
     class="btn btn-primary">
    Danish manual
  </a>

  <a href="https://steno-aarhus.github.io/registers-guide/en/"
     class="btn btn-primary">
    English manual
  </a>

</div>

## Code of conduct
-   To keep the cost of disk storage low aim to keep your personal workdata-folder below 50 GB pr. project. You can check this by placing the mouse on your personal folder.
-   As the Rawdata folder only contains read only data files, you cannot make any changes to data or write new files. To avoid unnecessary copies of rawdata your code/syntax should read data directly from this location. 
-   When working with data create one dataset based on your population and the needed variables.
-   Never keep more than one version of a dataset - several datasets quickly take up disk space.
-   Delete datasets when analyze are done. 
-   Make sure to save your code/syntax so you can always recreate your dataset.
-   A good advice is to keep track of research progress by documenting the files with a word or text file.  
-   Always close down programs and sign out by the end of the day. 




