---
title: "DST Registers and variables"
description: A description of all DST registers and variables in the projectdatabase.
---

## Registers from Statistics Denmark

<details>

<summary>**AEFV	2008-2023
**</summary>

| Variable name     | Variable label                                                         | Start year | Endyear |
| ----------------- | ---------------------------------------------------------------------- | ---------- | ------- |
| AEL_KOMKOD        | Kommunekode                                                            | 2008       | 2016    |
| ALDER_ULT         | Alder ultimo året                                                      | 2008       | 2016    |
| CPRTJEK           | CPR-tjek                                                               | 2008       | 2016    |
| CPRTYPE           | CPR-type                                                               | 2008       | 2016    |
| CVRNR             | Leverandørs CVR identifikation                                         | 2008       | 2016    |
| FRITVALGS_BEVIS   | FRITVALGS_BEVIS                                                        | 2008       | 2016    |
| FTI_MARK          | FTI_MARK                                                               | 2008       | 2016    |
| HAEND_MDR         | Hændelses måned.                                                       | 2008       | 2016    |
| LEV_TYPE_VIS      | Leverandør type for visiteret hjemmehjælp frit valg.                   | 2008       | 2016    |
| MAD_SERVICE       | MAD_SERVICE                                                            | 2008       | 2016    |
| PERPL_VIS         | Personlig pleje frit valg, gennemsnitlig visiteret tid pr. uge i minut | 2008       | 2016    |
| PNR               | Personnummer                                                           | 2008       | 2016    |
| PRAHJ_VIS         | Praktisk hjælp frit valg, gennemsnitlig visiteret tid pr. uge i minutt | 2008       | 2016    |
| SELVVALGTHJAELPER | SELVVALGTHJAELPER                                                      | 2008       | 2016    |
| VERSION           | VERSION                                                                | 2008       | 2016    |
| VISIT_FOERSTE     | Dato for første visitation.                                            | 2008       | 2016    |

</details>

<details>

<summary>**AEHJSP	2016-2023
**</summary>

| Variable name  | Variable label                 | Start year | Endyear |
| -------------- | ------------------------------ | ---------- | ------- |
| ALDER_ULT      | ALDER_ULT                      | 2016       | 2023    |
| CPRTJEK        | CPR-tjek                       | 2016       | 2023    |
| CPRTYPE        | CPR-type                       | 2016       | 2023    |
| CVRNR          | Leverandørs CVR identifikation | 2016       | 2023    |
| HAEND_MDR      | Hændelses måned                | 2016       | 2023    |
| HJEMSYGEP_DATO | HJEMSYGEP_DATO                 | 2016       | 2023    |
| IMP_MARK       | IMP_MARK                       | 2016       | 2023    |
| KOM            | INGEN LABEL                    | 2016       | 2023    |
| PNR            | PNR                            | 2016       | 2023    |
| VERSION        | VERSION                        | 2016       | 2023    |

</details>

<details>

<summary>**AEREHAB 2017-2018
**</summary>

| Variable name | Variable label | Start year | Endyear |
| ------------- | -------------- | ---------- | ------- |
| AEL_KOMKOD    | AEL_KOMKOD     | 2017       | 2018    |
| ALDER_ULT     | ALDER_ULT      | 2017       | 2018    |
| CPRTJEK       | CPR-tjek       | 2017       | 2018    |
| CPRTYPE       | CPR-type       | 2017       | 2018    |
| GODKEND_AAR   | GODKEND_AAR    | 2017       | 2018    |
| PNR           | PNR            | 2017       | 2018    |
| VERSION       | VERSION        | 2017       | 2018    |
| AAR           | AAR            | 2017       | 2018    |

</details>

<details>

<summary>**AETR 2008-2023
**</summary>

| Variable name | Variable label                                              | Start year | Endyear |
| ------------- | ----------------------------------------------------------- | ---------- | ------- |
| AEL_KOMKOD    | Kommunekode                                                 | 2008       | 2023    |
| ALDER_ULT     | Alder ultimo                                                | 2008       | 2023    |
| CPRTJEK       | CPR-tjek                                                    | 2008       | 2023    |
| CPRTYPE       | CPR-type                                                    | 2008       | 2023    |
| HAEND_MDR     | Hændelses måned.                                            | 2008       | 2023    |
| PNR           | Personnummer                                                | 2008       | 2023    |
| TRAEN_ART     | Markering af ydelse (genoptræning/ vedligeholdelsestræning) | 2008       | 2023    |
| VERSION       | Version                                                     | 2008       | 2023    |

</details>

<details>

<summary>**AKM 1976-2023
**</summary>

|     | Variable name        | Variable label                                                         | Start year | Endyear |
| --- | -------------------- | ---------------------------------------------------------------------- | ---------- | ------- |
| AKM | ALDER_ULT_INK        | Personens alder på referenecetidspunktet, 13 . 12. det pågældende år   | 1976       | 2023    |
| AKM | ANT_ANSAT_ARBSTED    | Antal ansatte for væsentligste arbejdssted ( optælling af ansatte sker | 1976       | 2023    |
| AKM | ANT_ANSAT_ARBSTED_13 | Antal ansatte for væsentligste arbejdssted ( optælling af ansatte sker | 1976       | 2023    |
| AKM | ANT_ANSAT_SENR       | Antal ansatte for væsentligste beskæftigelse                           | 1976       | 2023    |
| AKM | ATPSUM2              | Beskæftigelsesmål baseret på ATP- indbetalinger                        | 1976       | 2023    |
| AKM | BESKST               | Beskæftigelsesstatus 1980 til 2001                                     | 1976       | 2023    |
| AKM | BESKST02             | Beskæftigelsesstatus fra 2002                                          | 1976       | 2023    |
| AKM | BESKST13             | Kode for personens væsentligste indkomstkilde                          | 1976       | 2023    |
| AKM | BRANCHE_77           | Branchekode                                                            | 1976       | 2023    |
| AKM | BRCHI                | Branchekode for indehaver                                              | 1976       | 2023    |
| AKM | BRCHL                | Branchekode for lønmodtager                                            | 1976       | 2023    |
| AKM | CPRTJEK              | CPR-tjek                                                               | 1976       | 2023    |
| AKM | CPRTYPE              | CPR-type                                                               | 1976       | 2023    |
| AKM | DISCO_ALLE_INDK_13   | Fagklassifikation for beskæftigelsesforhold, fra 1991 TIL 2009         | 1976       | 2023    |
| AKM | DISCO08_ALLE_INDK    | Fagklassifikation for beskæftigelsesforhold, fra 2010                  | 1976       | 2023    |
| AKM | DISCO08_ALLE_INDK_13 | Fagkode for væsentligste beskæftigelse i året- fra 2010                | 1976       | 2023    |
| AKM | DISCO08_LOEN_INDK    | Fagkode for væsentligste lønmodtagerbeskæftigelse i året.              | 1976       | 2023    |
| AKM | DISCO08_SEL_INDK     | Fagkode for arbejde i selvstændig virksomhed                           | 1976       | 2023    |
| AKM | DISCOALLE_INDK       | Fagklassifikation for beskæftigelsesforhold, fra 1991 TIL 2009         | 1976       | 2023    |
| AKM | DISCOLOEN_INDK       | Fagkode for væsentligste lønmodtagerbeskæftigelse i året.              | 1976       | 2023    |
| AKM | DISCOSEL_INDK        | Fagkode for arbejde i selvstændig virksomhed                           | 1976       | 2023    |
| AKM | DISCOTYP             | Kilde til lønmodtager DISCO-koden                                      | 1976       | 2023    |
| AKM | FUNK_TIMEANT         | Personens samlede antal arbejdstimer i året.                           | 1976       | 2023    |
| AKM | NACE                 | Branche for væsentligste beskæftigelse, fra 1992 til 2007              | 1976       | 2023    |
| AKM | NACE_13              | Branche for væsentligste beskæftigelse, fra 1992 til 2007              | 1976       | 2023    |
| AKM | NACE_DB07            | Branche for væsentligste beskæftigelse, fra 2008                       | 1976       | 2023    |
| AKM | NACE_DB07_13         | Branche for væsentligste beskæftigelse, fra 2007                       | 1976       | 2023    |
| AKM | NACEA                | Branchegruppering for arbejdssted (1993 til 2007)                      | 1976       | 2023    |
| AKM | NACEA_DB07           | Branchegruppering for arbejdssted ( fra 2007)                          | 1976       | 2023    |
| AKM | NACEI                | Branchekode for selvstændige og medarbejdende ægtefællers virksomhed(1 | 1976       | 2023    |
| AKM | NACEI_DB07           | Branchegruppering for indehaver (Selvstændig eller medhjælpende ægtefæ | 1976       | 2023    |
| AKM | NYSTGR               | Stillingsgruppering 1980 til 1995                                      | 1976       | 2023    |
| AKM | OMFANG               | Omfang af skattepligt                                                  | 1976       | 2023    |
| AKM | PNR                  | Personnummer                                                           | 1976       | 2023    |
| AKM | SENR                 | SE-nummer for væsentligste beskæftigelse                               | 1976       | 2023    |
| AKM | SENRI                | SE-nummer for den virksomhed som personen ejer                         | 1976       | 2023    |
| AKM | SENRL                | SE-nummer for lønmodtager                                              | 1976       | 2023    |
| AKM | SOCIO                | Socioøkonomisk klassifikation fra 1994 til 2001                        | 1976       | 2023    |
| AKM | SOCIO_GL             | Socioøkonomisk klassifikation fra 1976 til 1990                        | 1976       | 2023    |
| AKM | SOCIO02              | Socioøkonomisk klassifikation fra 2002                                 | 1976       | 2023    |
| AKM | SOCIO13              | Socioøkonomisk klassifikation version 2013                             | 1976       | 2023    |
| AKM | TYP                  | Stillingstype                                                          | 1976       | 2023    |
| AKM | VERSION              | Version                                                                | 1976       | 2023    |
| AKM | VIRKF                | Virksomhedskode angiver hvilken form for ejerskab der er på den arbejd | 1976       | 2023    |
| AKM | VIRKF_13             | Virksomhedskode angiver hvilken form for ejerskab der er på den arbejd | 1976       | 2023    |
| AKM | VIRKFA               | Virksomhedskode angiver hvilken form for ejerskab der er på den arbejd | 1976       | 2023    |

</details>

<details>

<summary>**BEF 198512-202312
**</summary>

|     | Variable name       | Variable label                                            | Start year | Endyear |
| --- | ------------------- | --------------------------------------------------------- | ---------- | ------- |
| BEF | ADRESSE_ID          | INGEN LABEL                                               | 198512     | 202312  |
| BEF | AEGTE_ID            | Personnummer Ægtefælle                                    | 198512     | 202312  |
| BEF | ALDER               | Alder ultimo året før                                     | 198512     | 202312  |
| BEF | ANTBOERNF           | ANTBOERNF                                                 | 198512     | 202312  |
| BEF | ANTBOERNH           | ANTBOERNH                                                 | 198512     | 202312  |
| BEF | ANTEFAM             | ANTEFAM                                                   | 198512     | 202312  |
| BEF | ANTPERSF            | ANTPERSF                                                  | 198512     | 202312  |
| BEF | ANTPERSH            | ANTPERSH                                                  | 198512     | 202312  |
| BEF | BETALINGSKOM        | BETALINGSKOM                                              | 198512     | 202312  |
| BEF | BOP_VFRA            | Dato for tilflytning/indvandring                          | 198512     | 202312  |
| BEF | CIV_VFRA            | Civilstandsdato                                           | 198512     | 202312  |
| BEF | CIVST               | Civilstand                                                | 198512     | 202312  |
| BEF | CPRTJEK             | CPR-tjek                                                  | 198512     | 202312  |
| BEF | CPRTYPE             | CPR-type                                                  | 198512     | 202312  |
| BEF | E_FAELLE_ID         | PNR                                                       | 198512     | 202312  |
| BEF | FAM_KOEN            | FAM_KOEN                                                  | 198512     | 202312  |
| BEF | FAMILIE_ID          | Familiens identificerende nummer.                         | 198512     | 202312  |
| BEF | FAMILIE_TYPE        | Familietype                                               | 198512     | 202312  |
| BEF | FAR_ID              | Personnummer far                                          | 198512     | 202312  |
| BEF | FKIRK               | Folkekirkemarkering                                       | 198512     | 202312  |
| BEF | FM_MARK             | Forældremarkering                                         | 198512     | 202312  |
| BEF | FOED_DAG            | Fødselsdato                                               | 198512     | 202312  |
| BEF | FOEDREG_KODE        | Kode for personens fødselsregistreringssted.              | 198512     | 202312  |
| BEF | FOERSTE_INDVANDRING | Første indvandringsdato                                   | 198512     | 202312  |
| BEF | HUSTYPE             | Husstandstype                                             | 198512     | 202312  |
| BEF | IE_TYPE             | Indvandrere, efterkommere , personer med dansk oprindelse | 198512     | 202312  |
| BEF | KOEN                | Køn                                                       | 198512     | 202312  |
| BEF | KOM                 | Kommunekode                                               | 198512     | 202312  |
| BEF | MOR_ID              | Personnummer mor                                          | 198512     | 202312  |
| BEF | OPHOLDMD_DK         | OPHOLDMD_DK                                               | 198512     | 202312  |
| BEF | OPR_LAND            | Oprindelsesland                                           | 198512     | 202312  |
| BEF | PLADS               | Familiestatus                                             | 198512     | 202312  |
| BEF | PNR                 | Personnummer                                              | 198512     | 202312  |
| BEF | REFERENCETID        | REFERENCETID                                              | 198512     | 202312  |
| BEF | REG                 | Region                                                    | 198512     | 202312  |
| BEF | SENESTE_INDVANDRING | SENESTE_INDVANDRING                                       | 198512     | 202312  |
| BEF | STATSB              | Statsborgerskab                                           | 198512     | 202312  |
| BEF | VAN_VTIL            | Indvandringsdato                                          | 198512     | 202312  |
| BEF | VERSION             | VERSION                                                   | 198512     | 202312  |

</details>

<details>

<summary>**BEFADR 202409
**</summary>

|        | Variable name | Variable label                             | Start year | Endyear |
| ------ | ------------- | ------------------------------------------ | ---------- | ------- |
| BEFADR | ADR_RFRA      | Adressedato gældende fra (registerdato)    |            | 202409  |
| BEFADR | ADR_VFRA      | Adressedato - gældende fra (hændelsesdato) |            | 202409  |
| BEFADR | ADR_VTIL      | Adressedato - gældende til (hændelsesdato) |            | 202409  |
| BEFADR | ADRESSE_ID    |                                            |            | 202409  |
| BEFADR | BOPIKOM       | Bopælsadresse i kommunen                   |            | 202409  |
| BEFADR | KOM           | KOM                                        |            | 202409  |
| BEFADR | OPGIKOM       | Opgangsadresse i kommunen                  |            | 202409  |

</details>

<details>

<summary>**BFL 2008-2024
**</summary>

|     | Variable name              | Variable label                                                         | Start year | Endyear |
| --- | -------------------------- | ---------------------------------------------------------------------- | ---------- | ------- |
| BFL | AJO_ARB_KOMKODE            | Arbejdsstedets kommunekode                                             | 2008       | 202403  |
| BFL | AJO_ARBNR_SENR             | Entydigt 10-cifret identifikationsnummer for et arbejdssted            | 2008       | 202403  |
| BFL | AJO_ATP_BELOEB             | Indbetalt ATP-bidrag                                                   | 2008       | 202403  |
| BFL | AJO_ATP_BIDRAG_SATS_KODE   | ATP-bidragssats på jobbet                                              | 2008       | 202403  |
| BFL | AJO_BRANCHE07              | DB07 branche knyttet til jobbets arbejdssted                           | 2008       | 202403  |
| BFL | AJO_BREDT_LOENBELOEB       | Bredt lønbeløb er en summering af al lønindkomst i eIR                 | 2008       | 202403  |
| BFL | AJO_CVR_NR_FRA_PROD_JOB    | Indberetterens CVR-nummer fra prodjob                                  | 2008       | 202403  |
| BFL | AJO_FIKTIV_ARB_KODE        | Fiktiv arbejdssteds kode på det komprimerede prodjob                   | 2008       | 202403  |
| BFL | AJO_FULDTID_BESKAEFTIGET   | Fuldtidsbeskæftigelse                                                  | 2008       | 202403  |
| BFL | AJO_FUNKTIONSKODE          | Funktionskode til sektorplacering af arbejdsstedet                     | 2008       | 202403  |
| BFL | AJO_INDBERETTEDE_LOENTIMER | Løntimer på prodjob                                                    | 2008       | 202403  |
| BFL | AJO_INDKOMST_ART_KODE      | Indkomstartkode på prodjob                                             | 2008       | 202403  |
| BFL | AJO_INDKOMST_TYPE_KODE     | Indkomsttypekode på prodjob                                            | 2008       | 202403  |
| BFL | AJO_JOB_SLUT_DATO          | Slutdato for det komprimerede job                                      | 2008       | 202403  |
| BFL | AJO_JOB_START_DATO         | Startdato for det komprimerede job                                     | 2008       | 202403  |
| BFL | AJO_LOENTIME_KODE          | Kode for, om løntimer er indberettet eller imputeret                   | 2008       | 202403  |
| BFL | AJO_LOENTIMER              | Løntimer på komprimerede job                                           | 2008       | 202403  |
| BFL | AJO_OK_NR                  | Økonomisk enhed (statistisk enhed)                                     | 2008       | 202403  |
| BFL | AJO_PROD_NR_FRA_APP        | Produktionsenhedsnummer ifølge APP på prodjob                          | 2008       | 202403  |
| BFL | AJO_PROD_NR_FRA_PROD_JOB   | Produktionsenhedsnummer indberettet på et komprimeret prodjob          | 2008       | 202403  |
| BFL | AJO_SE_NR_FRA_PROD_JOB     | Indberetterens SE-nr. på prodjob.                                      | 2008       | 202403  |
| BFL | AJO_SMALT_LOENBELOEB       | Smalt lønbeløb, som omfatter lønindkomst uden ATP-bidrag og personaleg | 2008       | 202403  |
| BFL | ANTAL_LOENMODTAGER_JOB     | ANTAL_LOENMODTAGER_JOB                                                 | 2008       | 202403  |
| BFL | ANTAL_LOENMODTAGERE        | ANTAL_LOENMODTAGERE                                                    | 2008       | 202403  |
| BFL | CPRTJEK                    | CPR-tjek                                                               | 2008       | 202403  |
| BFL | CPRTYPE                    | CPR-type                                                               | 2008       | 202403  |
| BFL | PNR                        | Personnummer                                                           | 2008       | 202403  |
| BFL | SEKTORKODE                 | Sektor kode                                                            | 2008       | 202403  |
| BFL | VMO_DISCO_KODE             | DISCO kode                                                             | 2008       | 202403  |
| BFL | VMO_DISCO_MATCHPRIO_KODE   | DISCO match prioriterings kode                                         | 2008       | 202403  |
| BFL | VMO_DISCO_SLUT_DATO        | Slutdato for DISCO kode                                                | 2008       | 202403  |
| BFL | VMO_DISCO_START_DATO       | Startdato for DISCO kode på lønindberetning                            | 2008       | 202403  |

</details>

<details>

<summary>**BOERNFB 2015-2021
**</summary>

|         | Variable name  | Variable label                  | Start year | Endyear |
| ------- | -------------- | ------------------------------- | ---------- | ------- |
| BOERNFB | BORN_VFRA      | Indmeldelsestidspunkt           | 2015       | 2021    |
| BOERNFB | BORN_VTIL      | Udmeldelsestidspunkt            | 2015       | 2021    |
| BOERNFB | CPRTJEK        | CPR-tjek                        | 2015       | 2021    |
| BOERNFB | CPRTYPE        | CPR-type                        | 2015       | 2021    |
| BOERNFB | DKOM           | DKOM                            | 2015       | 2021    |
| BOERNFB | DST_INSTNR     | DST_INSTNR                      | 2015       | 2021    |
| BOERNFB | EJER_BP        | EJER_BP                         | 2015       | 2021    |
| BOERNFB | FULDTID_BORN   | FULDTID_BORN                    | 2015       | 2021    |
| BOERNFB | I_NORMERING    | I_NORMERING                     | 2015       | 2021    |
| BOERNFB | KALDINST       | KALDINST                        | 2015       | 2021    |
| BOERNFB | PASNINGSTILBUD | PASNINGSTILBUD                  | 2015       | 2021    |
| BOERNFB | PNR            | PNR                             | 2015       | 2021    |
| BOERNFB | TIMER          | Kommunalt angivet pasningstimer | 2015       | 2021    |
| BOERNFB | VERSION        | VERSION                         | 2015       | 2021    |
| BOERNFB | AAR            | AAR                             | 2015       | 2021    |

</details>

<details>

<summary>**BOERNPRI 2018-2023
**</summary>

|          | Variable name     | Variable label    | Start year | Endyear |
| -------- | ----------------- | ----------------- | ---------- | ------- |
| BOERNPRI | CPRTJEK           | CPR-tjek          | 2018       | 2023    |
| BOERNPRI | CPRTYPE           | CPR-type          | 2018       | 2023    |
| BOERNPRI | INST_TYPE_BORNPAS | INST_TYPE_BORNPAS | 2018       | 2023    |
| BOERNPRI | KOM               | INGEN LABEL       | 2018       | 2023    |
| BOERNPRI | PNR               | PNR               | 2018       | 2023    |
| BOERNPRI | VERSION           | VERSION           | 2018       | 2023    |

</details>

<details>

<summary>**BOERNSB 2015-2023
**</summary>

|         | Variable name | Variable label | Start year | Endyear |
| ------- | ------------- | -------------- | ---------- | ------- |
| BOERNSB | ALDER_OKT     | INGEN LABEL    | 2015       | 2023    |
| BOERNSB | CPRTJEK       | CPR-tjek       | 2015       | 2023    |
| BOERNSB | CPRTYPE       | CPR-type       | 2015       | 2023    |
| BOERNSB | CVRNR         | INGEN LABEL    | 2015       | 2023    |
| BOERNSB | EJER2         | EJER2          | 2015       | 2023    |
| BOERNSB | INSTNRBP      | INGEN LABEL    | 2015       | 2023    |
| BOERNSB | INSTTYPE2     | INSTTYPE2      | 2015       | 2023    |
| BOERNSB | KOM           | INGEN LABEL    | 2015       | 2023    |
| BOERNSB | PNR           | PNR            | 2015       | 2023    |
| BOERNSB | SKOLE_KODE    | INGEN LABEL    | 2015       | 2023    |
| BOERNSB | VERSION       | VERSION        | 2015       | 2023    |

</details>

<details>

<summary>**CPST 197512-200612
**</summary>

|      | Variable name  | Variable label                                               | Start year | Endyear |
| ---- | -------------- | ------------------------------------------------------------ | ---------- | ------- |
| CPST | AEGTEFAELLE_ID | Ægtefælles PNR                                               | 197512     | 200612  |
| CPST | BOPIKOM        | Adressen (vej, husnummer, husbogstav, etage, side/dørnummer) | 197512     | 200612  |
| CPST | CIVDATO        | Civilstandsdato                                              | 197512     | 200612  |
| CPST | CIVST          | Civilstand                                                   | 197512     | 200612  |
| CPST | FAR_ID         | PNR for far                                                  | 197512     | 200612  |
| CPST | KOM            | Bopæls kommune                                               | 197512     | 200612  |
| CPST | MOR_ID         | PNR for mor                                                  | 197512     | 200612  |
| CPST | OPGIKOM        | Opgangsadresse i kommunen                                    | 197512     | 200612  |
| CPST | PNR            | Personnummer                                                 | 197512     | 200612  |
| CPST | STOPHDTO       | Startdato for opholdsgrundlag                                | 197512     | 200612  |
| CPST | VAN_VFRA       | udvandringsdato                                              | 197512     | 200612  |
| CPST | VAN_VTIL       | Indvandringsdato                                             | 197512     | 200612  |

</details>

<details>

<summary>**DOD 2023
**</summary>
