---
title: "Registration on RM Record (RM Fortegnelse)"
description: |
  Description on how to register you project on the Internal record at Region Midtjylland
---

## RM Record

All research projects under SDCA's project database must be registered on the Internal record at Region Midtjylland.

Information on registration and link to registration form can be found here:

[Registrering af projekt på intern fortegnelse](https://www.fagperson.sundhed.rm.dk/forskning-og-innovation/lovkrav-til-forskning-og-innovation/registrering-af-projekt-pa-intern-fortegnelse/)

## Registration

You can register your project here:

[Registreringsblanket](https://selvbetjening.rm.dk/rm/Login/LoginFederated?returnUrl=/rm/Opret/5b3a680550190)

The registration must contain the following information:

-   

    1.  Project type, title and purpose

-   

    2.  Project responsible and contact person if applicable

-   

    3.  Where is the data processed?

-   

    4.  General description of the project

-   

    5.  Number of people in the population, person categories and data types

-   

    6.  Legal basis

-   

    7.  External disclosure of information

-   

    8.  Internal processing of data

-   

    9.  Receiving information

-   

    10. Start date, end date and special considerations

-   

    11. Security and submission

-   

    12. Summary and approval

For more information see: [Vejledning til udfyldelse](https://www.fagperson.sundhed.rm.dk/siteassets/forskning/regler/anmeldelse-til-vek/anmeldelse-af-nyt-projekt/vejledning-til-udfyldelse-af-anmeldelse-af-offentligt-videnskabeligt-forskningsprojekt.pdf)
