---
title: "DST Project application"
description: Information on how to make a project application in DDV
---

To set up a subproject under the Project Database at SDCA you need to make a project application i "Danmarks Datavindue". 

Guide to project application:

Log in to remote.dst.dk with your DST log in details. Go to the “Denmark Data Window” (top left) on the f5 remote desktop. A new “DDV” tab will open. Log into DDV.  

Choose DATA ORDERS and click on "New project proposal". Type the title of the project and choose the institution "574 - Steno Diabetes Center Aarhus (SDCA), Aarhus Universitetshospital" 
- choose Scheme "Projektdatabaseordning (709627)".

Under "PROJECT DETAILS" you need to describe:
- The title of the projct: The project title should be short and precise.

- The purpose: Describe the overall purpose of the project.

Support questions:
What is the overall purpose of the study?
What will be achieved as a result of the study?
How is the purpose defined?

Recommendation:
Keep the purpose statement short, precise and in layman's terms.
Avoid repeating things that belong in the project description or population.
Pay attention to the context of the rest of the project setting.

- Description: Based on the purpose of the project, explain the background and conditions for the study itself.

Help questions:
What field of study does the project address?
Which hypothesis or research questions are being investigated or answered?
Why is the population composed as it is (argumentation for composition, size and data basis)

Especially regarding the argumentation for data use in the project description:
Which topics are affected by the project, and how are basic data and any external data used in relation to these topics.
When describing data, general terms such as “socio-demographic registers” or “health data” are not sufficient. Instead, use delimiting concepts such as “immigration”, “education”, “crime” and “income” as well as “diagnostic information”, “pharmaceutical data” and “tariffs” in these examples.
Argumentation for external data is described in the same way as basic data. This applies to data for analysis purposes as well as for population formation.
Recommendations:
Be aware that it is the responsibility of the data controller to ensure that the approved project setting reflects, argues for and documents all data associated with the project
Remember to select basic data under data content and describe external data under “Other data”. Changes after project approval will require a resetting.
Be aware of the link between the description and the other parts of the project setting.

- Importance to society: Briefly describe the social relevance of the project.

Help questions:
What is the link between project purpose and community relevance?
How is the project relevant to society as a whole?
Publication alone does not constitute social relevance. 
Recommendations:
Keep the description concise and credible.
Avoid repetitions from the rest of the text and text that does not relate to this specific project.

Under "PROJECT ACCESS" you can add the people who should have access to the project and assign roles and rights.

Under "DATA CONTENT" you can define the population/populations, data content and select registers and variables. 

Requirements for the population description:
The population must be described so that it is clear what it consists of (persons, companies, addresses, a unique combination of several factors or other), what year or period the population should cover regardless of size. The population must also be defined, justified and delimited according to the purpose. If a full population is desired, an argument for this must be stated in the population description.
A good population description should include one or more of the following elements:
Which registers or external/other data will be used in the population formation.
Which period/year/quarter/month should be used.
Which conditions must be met, preferably by actually writing the conditions with variable names and delimitation on specific values. For example, that the population should be limited by age from 15-76 years.
Who will form the population(s).
Possibly how the registers should be linked if multiple registers are to be used. Linking based on which variables and possibly via which key register. (This can be specified in an extract description that is attached in the Danish Data Window).
The extract description should be attached to the population description if the population is specially conditioned, linked or otherwise. This applies even if the population is created externally.

How to choose data:

- Data from the Projectdatabase (709627): Here you can select data that already exists in the Project database.

- Data from Denmarks Data Portal: Here it is possible to purchase registers from Statistics Denmark that are not already in the Projekt database.

- Additional datasources: Here you describe data that does not come from Statistics Denmark, e.g. data from SDS, RKKP, your own data...
Here a variable lists with a description of the data must be attached.

Under "ANALYTICS PLATFORMS" choose "Server SDCA".

Under "SUMMARY" you can review your project proposal and check that everything is entered correctly. If you want to change something, you can go back and correct it before submitting your proposal.
If you are the administrator of the institution the project is under, you can send the proposal directly to Statistics Denmark (“Submit”) otherwise you need to send the it to send it to the administrators (“Send to administrator”) at your institution (the Data Management Team). 
If you get your proposal back for review, it means that your project manager at Statistics Denmark has reviewed it and added comments for you to consider. You can resubmit your project option once you have made the corrections.

For more inspiration: Find guidelines and inspiration to DDV on DST's homepage:
[How to use DDV] (https://www.dst.dk/da/TilSalg/Forskningsservice/danmarks-datavindue)

